### Register user
POST {{BASE_URL}}/auth/register
Content-Type: application/json

{
  "username": "HttpUser",
  "email": "httpuser@mail.com",
  "password": "Pa$$w0rd"
}

### Login user
# @name login
POST {{BASE_URL}}/auth/login
Content-Type: application/json

{
  "email": "httpuser@mail.com",
  "password": "Pa$$w0rd"
}

> {%
    client.global.set("refresh_token", response.body.refreshToken);
    client.global.set("access_token", response.body.accessToken);
%}

### Refresh token
POST {{BASE_URL}}/auth/refresh-token
Content-Type: application/json

{
    "refreshToken": "{{refresh_token}}"
}

> {% client.global.set("access_token", response.body.accessToken);%}