GET {{ BASE_URL }}/beacon/6/notification/83
Authorization: Bearer {{access_token}}

### Post reply
POST {{ BASE_URL }}/beacon/9/notification/142
Content-Type: application/json
Authorization: Bearer {{access_token}}


{
  "replyTextKey": "sad",
  "replyTextId": 1
}

### get notifs
GET {{ BASE_URL }}/beacon-notification?take=10&skip=0
Content-Type: application/json
Authorization: Bearer {{access_token}}
