POST {{BASE_URL}}/community-room/posts/room/cmelsvk000000l0p5ywpbg4zz
Content-Type: application/json
Authorization: Bearer {{access_token}}

{
  "title": "Testing Delete Post",
  "content": "This is a post created via HTTP client.",
  "moodFace": 50
}

### delete post
DELETE {{BASE_URL}}/community-room/posts/7
Content-Type: application/json
Authorization: Bearer {{access_token}}