### Settings API Requests
### Post location setting
POST {{BASE_URL}}/location-setting
Content-Type: application/json
Authorization: Bearer {{access_token}}

{
  "geohash": "something",
  "beaconRadius": 1000
}
### Get users and their locations setttings
GET {{BASE_URL}}/location-setting/users
Authorization: Bearer {{access_token}}

### Post notification setting
POST {{BASE_URL}}/notification-setting
Content-Type: application/json
Authorization: Bearer {{access_token}}

{
  "push": true,
  "maxBeaconPushes": 3,
  "minBeaconPushInterval": 7200
}