services:
  server:
    build:
      context: ../
      dockerfile: ./apps/server/Dockerfile
    container_name: beacon-server
    restart: always
    env_file:
      - ../.env.production
    expose:
      - "4000"
    depends_on:
      - db
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.beacon.rule=Host(`projects.geraldineho.co.uk`) || Host(`www.projects.geraldineho.co.uk`)"
      - "traefik.http.routers.beacon.entrypoints=websecure"
      - "traefik.http.routers.beacon.tls.certresolver=letsencrypt"
      - "traefik.http.services.beacon.loadbalancer.server.port=4000"

  db:
    image: postgres:15-alpine
    container_name: beacon-db
    restart: always
    environment:
      POSTGRES_USER: beacon
      POSTGRES_PASSWORD: beaconpassword
      POSTGRES_DB: beacon
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  traefik:
    image: traefik:v3.1
    container_name: traefik
    restart: always
    command:
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.letsencrypt.acme.httpchallenge=true"
      - "--certificatesresolvers.letsencrypt.acme.httpchallenge.entrypoint=web"
      - "--certificatesresolvers.letsencrypt.acme.email=your@email.com"
      - "--certificatesresolvers.letsencrypt.acme.storage=/letsencrypt/acme.json"
      - "--entrypoints.web.http.redirections.entryPoint.to=websecure"
      - "--entrypoints.web.http.redirections.entryPoint.scheme=https"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./letsencrypt:/letsencrypt"

volumes:
  postgres_data:
