services:
  server:
    build:
      context: ../
      dockerfile: ./apps/server/Dockerfile
    container_name: beacon-server
    restart: always
    env_file:
      - ../.env.production
    expose:
      - "4000:4000"
    depends_on:
      - db

  db:
    image: postgres:15-alpine
    container_name: beacon-db
    restart: always
    environment:
      POSTGRES_USER: beacon
      POSTGRES_PASSWORD: beaconpassword
      POSTGRES_DB: beacon
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data:
